### PR TITLE
Update unit tests for RecordSelectionDialog tabbed redesign

### PR DESCRIPTION
**Pull request by kphanee**
This CL updates unit tests for the code changes done as part
of CL #777 - Tabbed RecordSelectionDialog UX.

BUG: #739

### CODE REVIEW

**Comment by kphanee** [comment]
@natduca , @dj2 : PTAL!

This patch is dependent on #777. It needs to be merged only after #777 is merged.

**Comment by dj2** [comment]
Why isn't this part of #777 if it's updating tests?

**Comment by kphanee** [comment]
I just thought that keeping the tests as separate request would make it easier for you to review. :).
I can merge these changes to be part of #777 itself, if that is more convenient for review. :)

**Comment by dj2** [comment]
Lets keep the CL together. That way the tests stay working and we can see everything at one time.

**Comment by kphanee** [comment]
Sure. I will merge this patch to #777 and update it. I will close this.

**Pull request closed without merging**
