### PR TITLE
Redesign the RecordSelectionDialog to use tabbed interface

### PR DESCRIPTION
**Pull request by kphanee**
As per discussion in #739, the current interface for switch
between preset modes and manual mode (for presets or manual
selection option) is not intutive. Modifying the interface
to use tabbed interface.
On "Presets" tab, we only show the default presets. On any
customization of the default presets or selection of manual
selection mode, we automatically switch to the "Advanced" tab.

The working behavior is same as earlier - this is just a UX
change for achieving the earlier working behavior.

BUG: #739

R=nduca,dsinclair

### CODE REVIEW

**Comment by kphanee** [comment]
@natduca , @dj2 : As per discussion in #739, especially the last 5 comments of the issue, I have put these patch which moves the design to the tabbed interface for RSD.
PTAL and let me know your thoughts.
I will posting few snapshots of how the new UX looks with tabbed interface.
I will be adding few new unittests for new functionality and will be uploading the new tests in next patch.

**Comment by kphanee** [comment]
**RSD on launch when last selected option is Preset**
rsd_on_launch_when_preset_is_default
**RSD when we choose new preset option after launch**
rsd_on_change_of_prseset
**RSD when we 'click' on 'Customize...' option against chosen preset**
*In advanced tab, the preset included categories are already selected*
*Earlier (de)selected categories in 'Manual select settings' mode  are __not__ selected in this mode*
rsd_moved_to_adv_tab_on_customize
**RSD when 'Manually select settings' is last chosen preset**
rsd_on_launch_when_manual_is_default
**RSD when we 'click' on 'Presets' tab from Advanced tab**
rsd_moved_to_preset_in_manual

**Comment by kphanee** [comment]
@natduca @dj2 : I have updated the unit tests as per this CL code changes in #780 .
PTAL!

**Comment by dj2** [comment]
I don't think we need Manually select settings anymore as that's just the same thing as Advanced, isn't it?

**Comment by kphanee** [comment]
The concept of preset selection is still same as today. "Manually select settings" is required in case I want to choose a category set myself. When we move to Advanced by clicking "Customize" on any of the preset option, only the categories which are included as part of selected preset are pre-selected.
The categories saved in the DB (which is updated whenever user manually selects categories himself in manual mode) are not present in this case. Any modification to the selection doesn't update the DB. 

So, in case I want to choose a set of categories completely random, I still need "Manually select settings". Probably I can rename the preset something better?

**Comment by kphanee** [comment]
Updated the CL with the unit tests (earlier raised in #780) also as suggested by @dj2. PTAL!

**Comment by kphanee** [comment]
Gentle ping!!! :)

**Comment by natduca** [comment]
The "manual select settings" makes no sense. Lets remove that and add it again later when the concrete use case is more clear.

**Comment by kphanee** [comment]
If we remove "manual select settings", then I will not be able to run the following usecase:
To select completely new set of categories which are not part of any of the preset options.
For such usecase, I would have to choose one of the preset options, customize it to select all new categories.

Worse, these options selected wouldn't be saved into db since the flow of action was triggered by customize of a preset. We do need the option - probably we can give better name for the option.

**Comment by natduca** [comment]
Um, Why can't you just click the advanced tab?

**Comment by kphanee** [comment]
IMHO, if we add 'click' handler for advanced tab and use it for manual selection, it will become lot more confusing.
The behavior of advanced tab when we click on it to the behavior when it is opened by customize option will be different. This would cause more confusion on when which type of behavior is invoked.

One alternative, I can think of is below:
When we click on customize button, show a  'tab' with heading as 'Customize preset...', which will show the same category column view but with preset categories selected. Probably we can hide it by default and show only when 'customize...' option is invoked.

In that case, Advanced becomes the regular manual selection mode on which we can click at any time. to get the db stored categories and we can move back to preset tab any time. WDYT?

**Comment by natduca** [comment]
Wait, what? Why can't you click the advanced tab?

I'm starting to think that maybe this bug is not a good match for you,
Ravi. I'm sorry, but this task is going in circles.

**Comment by kphanee** [comment]
Ok. I can quickly make the changes to the behavior flow you have described:

* Two tabs - Preset and Advanced
* Preset tab - use any of the preset mode option
* If we click advanced, it shows the last advanced categories used last time the advanced category tab was open (read from settings db).
* If we click customize on preset options, it would switch to the advanced tab, configure the advanced tab to the presets.
* If the user re-records, and had advanced tab selected before, advanced tab would reappear.
* If the user re-records and had preset tab selected before, preset tab with previous mode reappear.

In this flow I agree, manual select settings is no longer required and I will remove it from preset options.

Also, about using tab_view.html component, I have used the tab-strip element from the tab_view.html component only. But I placed the RSD input elements in plain div and packed along with tab-strip element, to get a tab-like ui. Instead of plain div, I will try to use the tab-content-container element instead.

**Comment by dj2** [comment]
Closing this as it's been several months, please push a CL to rietveld if this is still open.

**Pull request closed without merging**
